server {
    listen 80;

    location /clients/ {
        proxy_pass http://localhost:5000;
    }

    location /products/ {
        proxy_pass http://localhost:5001;
    }

    location /inventory/ {
        proxy_pass http://localhost:5002;
    }

    location /user/ {
        proxy_pass http://localhost:5003;
    }
}