apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: "rds-mysql-app.ch0a95p2cmpz.us-east-1.rds.amazonaws.com"
  DB_USER: "ArthurMilani"
  DB_PASSWORD: "pacote321"
